#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# Janus Init Config Steps
# ----------------------------------------------------------------------------
# This file generates and finalizes janus.conf.
# ----------------------------------------------------------------------------

if [ -n "${JANUS_INIT_STEP_CONFIG_LOADED:-}" ]; then
    return 0 2>/dev/null || exit 0
fi
JANUS_INIT_STEP_CONFIG_LOADED=1

# Detect the host distribution from /etc/os-release.
janus_init_detect_distro() {
    if [ -f /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        printf '%s' "${PRETTY_NAME:-$NAME}"
        return 0
    fi

    printf '%s' "Unknown"
}

# Create janus.conf when missing.
janus_init_create_config() {
    if [ -f "$JANUS_INIT_CONF_FILE" ]; then
        janus_init_log_ok "Configuration file already exists: janus.conf"
        return 0
    fi

    janus_init_log_info "Generating base janus.conf"

    cat > "$JANUS_INIT_CONF_FILE" <<EOF_CONF
# ----------------------------------------------------------------------------
# Janus configuration file
# Generated by janus-init
# ----------------------------------------------------------------------------

JANUS_VERSION="$JANUS_INIT_VERSION"

# Host information
HOST_DISTRO="$(janus_init_detect_distro)"
HOST_KERNEL="$(uname -r)"

# Core settings
VM_BACKEND="libvirt"
GPU_MODE="unset"
LOOKING_GLASS="disabled"

# Safety flags
INIT_COMPLETE="false"
EOF_CONF

    [ -f "$JANUS_INIT_CONF_FILE" ] || janus_init_die "Failed to create configuration file: $JANUS_INIT_CONF_FILE"

    janus_init_log_ok "janus.conf created"
}

# Mark initialization as completed in janus.conf.
janus_init_finalize_config() {
    janus_init_log_info "Finalizing configuration flags"

    sed -i 's/INIT_COMPLETE="false"/INIT_COMPLETE="true"/' "$JANUS_INIT_CONF_FILE" \
        || janus_init_die "Could not update INIT_COMPLETE in $JANUS_INIT_CONF_FILE"

    janus_init_log_ok "Janus marked as initialized"
}
